### ISSUE TITLE
Angle between faces affectson beveling

### ISSUE THREAD

**Issue by valerioa** [Obijuan/obiscad#11]
Hi Juan,

I observed the following problem: beveling is correct only when the angle between the faces is 90 deg. If the angle is < 90 the bevel is acceptable, but it is geometrically incorrect, as it flattens more, the more acute the angle is. If the angle is > than 90 deg, the bevel is carved out.

<img width="1102" alt="image" src="https://user-images.githubusercontent.com/737428/51431496-c9962880-1be6-11e9-8529-3fd775363f48.png">

This is due, as you know, to the bevel being constructed out of  a cube.

I have a pull request that makes a geometrically correct bevel, irrespective of the angle between the faces, by building the beveling surface out of a triangular prism.

<img width="1131" alt="image" src="https://user-images.githubusercontent.com/737428/51431793-65c22e80-1beb-11e9-8a0f-fd7b932b1ccb.png">

The base of the triangular prism is built as (the base of the prism is green; the section of the cylinder that is subtracted from the prism is red) 

<img width="681" alt="image" src="https://user-images.githubusercontent.com/737428/51431621-dfa4e880-1be8-11e9-8cd6-cf87b8806d12.png">

With that, bconcave_corner_aux() becomes:

<pre>
module bconcave_corner_aux(cr,cres,l,th,alpha=90)
{

    a = cr * cos(90-(alpha/2));
    b = cr * sin(90-(alpha/2));
    d = b / sin(alpha/2);
    c = d * cos(alpha/2);
    e = d * cos(45+(alpha/2));
    f = d * sin(45+(alpha/2));
    
    difference() {
    translate([0,0,-l/2])
    linear_extrude(
        height = l,    
        center = false,
        convexity = 20,
        twist = 0)
    polygon(points=[
        [0-th,0-th],
        [e-th,f],
        [e,f],
        [f,e],
        [f,e-th]
    ], convexity=20);
    
    translate([(a+c)*cos(45),(a+c)*sin(45),0])
    color([1,0,0])
    cylinder(r=cr, h=l+1, center=true, $fn=4*(cres+1));
    }   
}
</pre>

In order for it to work correctly, the translations have to be removed from bconcave_corner()

<pre>
module bconcave_corner(cr=1,cres=4,th=1,l=10,ext_corner=false,alpha=90)
{
  //-- Locate the origin in the exterior edge
  if (ext_corner==true)
    //translate([0,0,0])
      bconcave_corner_aux(cr,cres,l,th,alpha=alpha);
  else
     //-- Locate the origin in the interior edge
     //translate([0.0, 0.0,0])
       bconcave_corner_aux(cr,cres,l,th,alpha=alpha);
}
</pre>

I came to this while trying to design a NEMA 17 body to be subtracted out of a motor mount:

<img width="406" alt="image" src="https://user-images.githubusercontent.com/737428/51431639-432f1600-1be9-11e9-969b-f582e1d65a5b.png">

with the original bconcave_corner_aux() it would look like:

<img width="369" alt="image" src="https://user-images.githubusercontent.com/737428/51431651-6c4fa680-1be9-11e9-89eb-f6c5ed2c18cd.png">

I have added an "alpha" argument to all modules. The argument defaults to 90 deg., thus this pull is fully backward compatible.

I will follow up with a pull request.

**Comment by Obijuan** [comment]
Pull request merged!

https://github.com/Obijuan/obiscad/pull/12

Thanks a lot for your contribution! :-)
