### ISSUE TITLE
Trouble in beveling the top edge of a cylinder

### ISSUE THREAD

**Issue by valerioa** [Obijuan/obiscad#8]
The short summary of my problem is that, in trying to bevel the top of a cylinder, I noticed some bevel segments are not oriented correctly.

![image](https://user-images.githubusercontent.com/737428/34228758-1640ad0c-e58f-11e7-8c3c-ed65c9099d56.png)

The image is generated with:

<pre>
use &lt;obiscad/bevel.scad&gt;
use &lt;obiscad/attach.scad&gt;

epsilon=1e-3;

function getBevelConnectors(p1, p2, ft1, ft2) = [ 
    [((p1+p2)/2), (p2-p1)/norm(p2-p1), 0],
    [((p1+p2)/2), (cross( ft1[2] - ft1[1], ft1[0] - ft1[1])  /
                   norm(cross( ft1[2] - ft1[1], ft1[0] - ft1[1]))  +
                     cross( ft2[2] - ft2[1], ft2[0] - ft2[1]) / 
                     norm(cross( ft2[2] - ft2[1], ft2[0] - ft2[1]))  ) /
                     norm((cross( ft1[2] - ft1[1], ft1[0] - ft1[1])  /
                   norm(cross( ft1[2] - ft1[1], ft1[0] - ft1[1]))  +
                     cross( ft2[2] - ft2[1], ft2[0] - ft2[1]) / 
                     norm(cross( ft2[2] - ft2[1], ft2[0] - ft2[1]))  )), 
     0 ] ];

translate([0,0,-10]) cylinder(r=20,h=10);

p = [ for(a=[0:10:360]) [cos(a)*20, sin(a)*20, 0] ];
    
union(){
      for(i=[0:1:len(p)-2]) {
        bc1 = getBevelConnectors(p[i], p[i+1], 
        [p[i], p[i+1]-[0,0,10], p[i+1]], 
        [p[i], p[i+1], [0,0,0]]) ;
      color([1,0,0])
          bevel(bc1[0], bc1[1],cr = 2, cres=50, l=norm(p[i+1]-p[i])+epsilon);
      }
};
</pre>

I wrote the following function to compute bevel connectors for any arbitrary edge:

p1 & p2 are the endpoints of the edge, ft1 & ft2 are two triangles lying on the faces separated by the edge. Triangle are needed to calculate connectors. Points of the triangles have to be ordered according to the right hand rule for proper vector calculations.

<pre>
function getBevelConnectors(p1, p2, ft1, ft2) = [ 
    [((p1+p2)/2), (p2-p1)/norm(p2-p1), 0],
    [((p1+p2)/2), (cross( ft1[2] - ft1[1], ft1[0] - ft1[1])  /
                   norm(cross( ft1[2] - ft1[1], ft1[0] - ft1[1]))  +
                     cross( ft2[2] - ft2[1], ft2[0] - ft2[1]) / 
                     norm(cross( ft2[2] - ft2[1], ft2[0] - ft2[1]))  ) /
                     norm((cross( ft1[2] - ft1[1], ft1[0] - ft1[1])  /
                   norm(cross( ft1[2] - ft1[1], ft1[0] - ft1[1]))  +
                     cross( ft2[2] - ft2[1], ft2[0] - ft2[1]) / 
                     norm(cross( ft2[2] - ft2[1], ft2[0] - ft2[1]))  )), 
     0 ] ];
</pre> 

It seems to me that, for a circle lying on the [x,y] plane at z=0, bevels are not oriented correctly for edges that are formed at angle >= 90 & angle <=135. And, symmetrically, at angle >=180 & angle <=225.

Images below show that connectors to generate all bevels are oriented correctly:

![image](https://user-images.githubusercontent.com/737428/34174995-1c98862a-e4b8-11e7-9dd7-9899d5a1cf72.png)

![image](https://user-images.githubusercontent.com/737428/34175035-404056de-e4b8-11e7-9f1c-a8ce39c31411.png)

I will provide updates, as I discover more.

**Comment by valerioa** [comment]
The problem is with the sign of the determinant of the triple product (cnormal_v * enormal_v *edge_v) in module bconcave_corner_attach_aux().

The sign appears to be rotated clockwise by 45 degrees.

An easy patch, to solve the problem, is to replace the following line in module bconcave_corner_attach_aux():

<pre>
s=sign2(det(cnormal_v,enormal_v,edge_v))
</pre>

with the line
<pre>
s=sign2(det([0,0,1], enormal_v, edge_v))
</pre>

With that,  all bevel corners are oriented correctly:

![image](https://user-images.githubusercontent.com/737428/34227990-5858247a-e58c-11e7-9ecb-353cddf6c5b5.png)

[0,0,1] is cnormal_v rotated 45 deg counterclockwise

I have not tested the patch with arbitrary spatial orientation. I don't know how general it is.

**Comment by valerioa** [comment]
The solution for the general case, for any arbitrary orientation in space is replacing the line in bconcave_corner_attach_aux():

<pre>
s=sign2(det(cnormal_v,enormal_v,edge_v))
</pre>

with the line:

<pre>
rollg=sign2(det(Tcnormal_v,enormal_v,edge_v))*anglev(Tcnormal_v, enormal_v);
</pre>

the determinant has to be calculated with Tcnormal_v, not cnormal_v. I will submit a pull request.

The following picture proves all bevel corners are oriented correctly, irrespective of position in 3d space.

<img width="808" alt="image" src="https://user-images.githubusercontent.com/737428/34238760-ab4fe008-e5c0-11e7-90b1-954fafd1031e.png">

**Comment by Obijuan** [comment]
Thanks a lot for your contribution! I will close the issue
